### ISSUE TITLE
Use LibevNetProvider as the default network provider

### ISSUE THREAD

**Issue by oleggator** [tarantool/tntcxx#18]
Use LibevProvider as the default network provider, because it works out of the box on any platform.
In that case, `DefaultNetProvider` may be renamed to `EpollNetProvider` because it depends on epoll.

Also, it solves the problem that `Connection` depends on epoll because imports `DefaultNetProvider` and can't be compiled on any platform except Linux.

**Comment by Korablev77** [comment]
Ok, it seems to be reasonable to remove default network provider and force users always explicitly choose the one. In this case let's rename DefaultNetProvider to EpollNetProvider.

**Comment by Korablev77** [comment]
Fixed: now if systems lacks epoll - libev is used as default.
